<?php

namespace NotesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuarioRepository extends EntityRepository
{
}
