notes_homepage:
    path:     /principal
    defaults: { _controller: NotesBundle:Default:index }

notes_crear:
    path:     /crear
    defaults: { _controller: NotesBundle:Default:crear }
    methods: [POST]

notes_eliminar:
    path:     /eliminar/{id}
    defaults: { _controller: NotesBundle:Default:eliminar }
    

notes_actualizar:
    path:     /actualizar/{id}
    defaults: { _controller: NotesBundle:Default:actualizar }

notes_editar:
    path:     /editar
    defaults: { _controller: NotesBundle:Default:editar }
    methods: [POST]

notes_login:
    path:     /login
    defaults: { _controller: NotesBundle:Default:login }

notes_entrar:
    path:     /entrar
    defaults: { _controller: NotesBundle:Default:entrar }    
    methods: [POST]
    
    
        
    